# fly.toml app configuration file generated for notes-young-violet-8006 on 2024-11-19T10:15:12-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notes-young-violet-8006'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
